[2023-11-12T16:32:39.351+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.firs_task manual__2023-11-12T16:17:24.913934+00:00 [queued]>
[2023-11-12T16:32:39.379+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.firs_task manual__2023-11-12T16:17:24.913934+00:00 [queued]>
[2023-11-12T16:32:39.381+0000] {taskinstance.py:1361} INFO - Starting attempt 4 of 4
[2023-11-12T16:32:39.416+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): firs_task> on 2023-11-12 16:17:24.913934+00:00
[2023-11-12T16:32:39.430+0000] {standard_task_runner.py:57} INFO - Started process 6918 to run task
[2023-11-12T16:32:39.435+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'firs_task', 'manual__2023-11-12T16:17:24.913934+00:00', '--job-id', '1392', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpbsmvog3p']
[2023-11-12T16:32:39.441+0000] {standard_task_runner.py:85} INFO - Job 1392: Subtask firs_task
[2023-11-12T16:32:39.577+0000] {task_command.py:416} INFO - Running <TaskInstance: first_dag.firs_task manual__2023-11-12T16:17:24.913934+00:00 [running]> on host 24f204fafe4d
[2023-11-12T16:32:39.808+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='yuriy.peretolchin@mail.com' AIRFLOW_CTX_DAG_OWNER='Peretolchin.YuS' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='firs_task' AIRFLOW_CTX_EXECUTION_DATE='2023-11-12T16:17:24.913934+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-12T16:17:24.913934+00:00'
[2023-11-12T16:32:39.812+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-12T16:32:39.816+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/dags/test.py']
[2023-11-12T16:32:39.837+0000] {subprocess.py:86} INFO - Output:
[2023-11-12T16:32:40.056+0000] {subprocess.py:93} INFO - python3: can't open file '/opt/***/dags/test.py': [Errno 2] No such file or directory
[2023-11-12T16:32:40.066+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-11-12T16:32:40.091+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-11-12T16:32:40.103+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=first_dag, task_id=firs_task, execution_date=20231112T161724, start_date=20231112T163239, end_date=20231112T163240
[2023-11-12T16:32:40.142+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1392 for task firs_task (Bash command failed. The command returned a non-zero exit code 2.; 6918)
[2023-11-12T16:32:40.176+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-12T16:32:40.245+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
