[2023-11-12T16:23:36.631+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.firs_task manual__2023-11-12T16:18:30.311142+00:00 [queued]>
[2023-11-12T16:23:36.684+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.firs_task manual__2023-11-12T16:18:30.311142+00:00 [queued]>
[2023-11-12T16:23:36.687+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 4
[2023-11-12T16:23:36.747+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): firs_task> on 2023-11-12 16:18:30.311142+00:00
[2023-11-12T16:23:36.771+0000] {standard_task_runner.py:57} INFO - Started process 6525 to run task
[2023-11-12T16:23:36.777+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'firs_task', 'manual__2023-11-12T16:18:30.311142+00:00', '--job-id', '1388', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpwq3krmdc']
[2023-11-12T16:23:36.809+0000] {standard_task_runner.py:85} INFO - Job 1388: Subtask firs_task
[2023-11-12T16:23:37.406+0000] {task_command.py:416} INFO - Running <TaskInstance: first_dag.firs_task manual__2023-11-12T16:18:30.311142+00:00 [running]> on host 24f204fafe4d
[2023-11-12T16:23:37.841+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='yuriy.peretolchin@mail.com' AIRFLOW_CTX_DAG_OWNER='Peretolchin.YuS' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='firs_task' AIRFLOW_CTX_EXECUTION_DATE='2023-11-12T16:18:30.311142+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-12T16:18:30.311142+00:00'
[2023-11-12T16:23:37.847+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-12T16:23:37.850+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/dags/test.py']
[2023-11-12T16:23:37.880+0000] {subprocess.py:86} INFO - Output:
[2023-11-12T16:23:38.202+0000] {subprocess.py:93} INFO - python3: can't open file '/opt/***/dags/test.py': [Errno 2] No such file or directory
[2023-11-12T16:23:38.211+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-11-12T16:23:38.238+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-11-12T16:23:38.249+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=first_dag, task_id=firs_task, execution_date=20231112T161830, start_date=20231112T162336, end_date=20231112T162338
[2023-11-12T16:23:38.279+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1388 for task firs_task (Bash command failed. The command returned a non-zero exit code 2.; 6525)
[2023-11-12T16:23:38.304+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-12T16:23:38.377+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
